version: "3"

services:

  tests:
    image: ethereumoptimism/integration-tests:latest
    volumes:
      - ./integration-tests:/integration-tests
      - ./docker/integration-tests/wait-for-l1-and-l2-and-contract-deployment.sh:/opt/wait.sh
    env_file:
      - docker-compose.env

  geth_l2:
    build: ./docker/go-ethereum
    image: optimism-gethl2
    volumes:
      - ./l2-node:/l2-node/l2:rw
      - ./docker/go-ethereum/wait-for-l1.sh:/bin/wait-for-l1.sh
    env_file:
      - docker-compose.env
    ports:
      - 8545:8545

  batch_submitter:
    build: ./docker/batch-submitter
    image: optimism-batch-submitter
    env_file:
      - docker-compose.env

volumes:
  geth:
